name: "Baby Care Tracker"
description: "Complete baby care tracking solution with persistent data, analytics, and device integration"
version: "2.0.0"
slug: "baby-care-tracker"
startup: "services"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web interface"
webui: "http://[HOST]:[PORT:8099]"
init: false
map:
  - "config:rw"
  - "ssl"
options:
  mqtt_broker: "core-mosquitto"
  mqtt_username: ""
  mqtt_password: ""
  database_type: "sqlite"
  log_level: "info"
  enable_analytics: true
  export_enabled: true
  timezone: "UTC"
schema:
  mqtt_broker: "str"
  mqtt_username: "str?"
  mqtt_password: "password?"
  database_type: "list(sqlite|postgresql)?"
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
  enable_analytics: "bool"
  export_enabled: "bool"
  timezone: "str"
image: "ghcr.io/tsanidisdev/baby-care-tracker-addon-{arch}"
