name: Baby Care Tracker
description: Complete baby care tracking solution with persistent data, analytics, and device integration
version: "1.0.8"
slug: baby_care_tracker
startup: services
build_from:
  armhf: "ghcr.io/home-assistant/armhf-base:3.18"
  armv7: "ghcr.io/home-assistant/armv7-base:3.18"
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.18"
  amd64: "ghcr.io/home-assistant/amd64-base:3.18"
  i386: "ghcr.io/home-assistant/i386-base:3.18"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
webui: "http://[HOST]:[PORT:8099]"
init: false
map:
  - config:rw
  - ssl
options:
  mqtt_broker: core-mosquitto
  mqtt_username: ""
  mqtt_password: ""
  database_type: sqlite
  log_level: info
schema:
  mqtt_broker: str
  mqtt_username: str?
  mqtt_password: password?
  database_type: list(sqlite|postgresql)?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
